services:
  myapp:
    build:
      context: .  # Build context is the current directory
      dockerfile: Dockerfile  # Use the Dockerfile named "Dockerfile"
    volumes:
      - /app/archive/logs:/app/logs  # Mount logs
      - /app/archive/cred:/app/cred  # env and other credentials files
      - /app/archive/config:/app/config # configiguration file
    #environment:
    #  - GOOGLE_APPLICATION_CREDENTIALS=/app/cred/service-account-key.json  # Add environment variables if needed
